In [1]:
# importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns',None)

In [2]:
# loading dataset
df = pd.read_csv('data/gurgaon_properties_outlier_treatment.csv')

In [3]:
df.head()

,property_type,society,sector,price,area,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,...,built_up_area,carpet_area,study room,servant room,store room,pooja room,others,furnishing_type,luxury_score,area_room_ratio
0,flat,dlf regal gardens,sector 90,1.29,1430.0,9021.0,Super Built up area 1702(158.12 sq.m.)Built Up...,3,3,3,...,1540.0,1430.0,1,0,0,0,0,2,174,476.666667
1,flat,ireo the grand arch,sector 58,2.20,1375.0,16000.0,Carpet area: 1375 (127.74 sq.m.),2,2,1,...,NaN,1375.0,0,0,0,1,0,1,49,687.500000
2,flat,ireo victory valley,sector 67,2.95,2436.0,12110.0,Super Built up area 2436(226.31 sq.m.)Built Up...,3,3,3+,...,2236.0,2036.0,0,1,0,1,0,1,165,812.000000
3,flat,puri emerald bay,sector 104,2.23,2250.0,9911.0,Super Built up area 2450(227.61 sq.m.)Carpet a...,3,4,3+,...,NaN,2250.0,0,1,0,0,0,1,159,750.000000
4,flat,raheja vedaanta,sector 108,0.70,1548.0,4522.0,Built Up area: 1548 (143.81 sq.m.)Carpet area:...,2,2,3,...,1548.0,1200.0,0,0,0,0,0,2,0,774.000000

In [4]:
# checking the missing values
df.isnull().sum()

property_type             0
society                   0
sector                    0
price                     0
area                      0
price_per_sqft            0
areaWithType              0
bedRoom                   0
bathroom                  0
balcony                  87
floorNum                 17
facing                  843
agePossession             0
super_built_up_area    1775
built_up_area          2050
carpet_area            1779
study room                0
servant room              0
store room                0
pooja room                0
others                    0
furnishing_type           0
luxury_score              0
area_room_ratio           0
dtype: int64

In [6]:
df.shape

(3690, 24)

**`super_built_up_area` column**

In [5]:
df['super_built_up_area'].isnull().sum()

np.int64(1775)

In [7]:
missing_percent = (df['super_built_up_area'].isnull().sum()/df.shape[0])*100
missing_percent

np.float64(48.1029810298103)

In [8]:
# checking the common missing values in super_build_up_area,built_up_area and carpet_area
df[(df['super_built_up_area'].isnull()) & (df['built_up_area'].isnull()) & (df['carpet_area'].isnull())]

Empty DataFrame
Columns: [property_type, society, sector, price, area, price_per_sqft, areaWithType, bedRoom, bathroom, balcony, floorNum, facing, agePossession, super_built_up_area, built_up_area, carpet_area, study room, servant room, store room, pooja room, others, furnishing_type, luxury_score, area_room_ratio]
Index: []

[0 rows x 24 columns]

In [9]:

((df['super_built_up_area'].isnull()) & (df['built_up_area'].isnull()) & (df['carpet_area'].isnull()))

0       False
1       False
2       False
3       False
4       False
        ...
3685    False
3686    False
3687    False
3688    False
3689    False
Length: 3690, dtype: bool

In [13]:
df[~((df['super_built_up_area'].isnull()) | (df['built_up_area'].isnull()) | (df['carpet_area'].isnull()))]

,property_type,society,sector,price,area,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,floorNum,facing,agePossession,super_built_up_area,built_up_area,carpet_area,study room,servant room,store room,pooja room,others,furnishing_type,luxury_score,area_room_ratio
0,flat,dlf regal gardens,sector 90,1.29,1430.0,9021.0,Super Built up area 1702(158.12 sq.m.)Built Up...,3,3,3,7.0,East,Relatively New,1702.0,1540.00,1430.00,1,0,0,0,0,2,174,476.666667
2,flat,ireo victory valley,sector 67,2.95,2436.0,12110.0,Super Built up area 2436(226.31 sq.m.)Built Up...,3,3,3+,14.0,South,Moderately Old,2436.0,2236.00,2036.00,0,1,0,1,0,1,165,812.000000
9,flat,emaar mgf emerald floors premier,sector 65,2.75,1975.0,13924.0,Super Built up area 1975(183.48 sq.m.)Built Up...,4,4,3,3.0,North-West,Relatively New,1975.0,1750.00,1650.00,1,1,0,0,0,1,113,493.750000
10,flat,ss the leaf,sector 85,1.20,970.0,12371.0,Super Built up area 1671(155.24 sq.m.)Built Up...,2,2,2,4.0,East,Relatively New,1671.0,1190.00,970.00,0,1,1,0,0,2,81,485.000000
11,flat,corona optus,sector 37c,1.22,1765.0,6912.0,Super Built up area 1765(163.97 sq.m.)Built Up...,3,4,3,5.0,South-East,Relatively New,1765.0,1665.00,1565.00,0,0,0,0,0,2,149,588.333333
17,flat,ashiana mulberry,sohna road,0.90,1465.0,6143.0,Super Built up area 1465(136.1 sq.m.)Built Up ...,2,2,3+,7.0,North-East,Moderately Old,1465.0,1100.00,1000.00,1,0,0,0,0,1,156,732.500000
19,flat,m3m skywalk,sector 74,1.52,1139.0,13345.0,Super Built up area 1400(130.06 sq.m.)Built Up...,2,2,3,6.0,South-East,Relatively New,1400.0,1250.00,1139.20,0,0,1,0,0,2,174,569.500000
24,flat,m3m golfestate,sector 65,5.50,3243.0,16960.0,Super Built up area 3243(301.28 sq.m.)Built Up...,3,4,3,3.0,North-East,Relatively New,3243.0,2803.00,2388.00,0,1,0,0,0,2,49,1081.000000
34,flat,the close north,sector 50,2.65,2350.0,11277.0,Super Built up area 2605(242.01 sq.m.)Built Up...,3,3,3+,3.0,South-East,Moderately Old,2605.0,2491.00,2350.00,0,1,0,0,0,2,174,783.333333
46,flat,la vida by tata housing,sector 113,1.32,1276.0,10345.0,Super Built up area 1276(118.54 sq.m.)Built Up...,2,2,2,3.0,North-East,Relatively New,1276.0,1199.00,1099.00,0,0,0,0,0,2,49,638.000000
47,flat,dlf regal gardens,sector 90,1.65,2215.0,7449.0,Super Built up area 2215(205.78 sq.m.)Built Up...,4,4,3+,8.0,East,Relatively New,2215.0,1900.00,1700.00,0,0,0,0,1,2,79,553.750000
51,flat,ireo skyon,sector 60,3.75,2800.0,13393.0,Super Built up area 2800(260.13 sq.m.)Built Up...,4,4,3,12.0,North,Relatively New,2800.0,2650.00,2350.00,0,1,0,0,0,1,49,700.000000
56,flat,dlf the skycourt,sector 86,1.55,1930.0,8031.0,Super Built up area 1930(179.3 sq.m.)Built Up ...,3,3,1,12.0,North-East,Relatively New,1930.0,1900.00,1350.00,0,0,0,1,0,1,153,643.333333
69,flat,corona optus,sector 37c,1.26,1738.0,7250.0,Super Built up area 1735(161.19 sq.m.)Built Up...,3,3,3,4.0,North-East,New Property,1735.0,1400.00,965.00,0,0,0,0,0,2,28,579.333333
72,flat,sare green parc 2,sector 92,0.75,1581.0,4744.0,Super Built up area 1454(135.08 sq.m.)Built Up...,3,3,3,2.0,East,Relatively New,1454.0,1415.00,1350.00,0,0,0,0,1,1,49,527.000000
73,flat,dlf the skycourt,sector 86,1.60,1929.0,8294.0,Super Built up area 1929(179.21 sq.m.)Built Up...,3,3,3+,9.0,North-East,Relatively New,1929.0,1548.00,1300.00,0,0,0,0,1,1,167,643.000000
80,flat,m3m skywalk,sector 74,2.45,2018.0,12141.0,Super Built up area 2018(187.48 sq.m.)Built Up...,3,3,3+,25.0,South-West,Relatively New,2018.0,1800.00,1614.00,1,0,0,0,0,2,137,672.666667
81,flat,vatika gurgaon,sector 83,0.85,950.0,8947.0,Super Built up area 1245(115.66 sq.m.)Built Up...,2,2,2,18.0,West,Moderately Old,1245.0,1100.00,950.00,0,0,0,1,0,1,119,475.000000
82,flat,paras dews,sector 106,0.95,1385.0,6859.0,Super Built up area 1385(128.67 sq.m.)Built Up...,2,2,3+,2.0,North,Relatively New,1385.0,940.00,845.00,0,0,0,0,0,2,49,692.500000
94,flat,paras dews,sector 106,1.20,1034.0,11605.0,Super Built up area 1665(154.68 sq.m.)Built Up...,3,3,3,12.0,North-West,Relatively New,1665.0,1145.00,1034.00,1,0,0,0,0,2,158,344.666667
101,flat,unitech the residences,sector 33,1.10,1110.0,9910.0,Super Built up area 1110(103.12 sq.m.)Built Up...,2,2,3,9.0,East,Moderately Old,1110.0,1100.00,1000.00,0,0,0,0,0,1,44,555.000000
102,flat,paras dews,sector 106,1.17,1760.0,6648.0,Super Built up area 1760(163.51 sq.m.)Built Up...,3,4,3+,12.0,West,Relatively New,1760.0,1186.00,1130.00,0,1,0,0,0,2,49,586.666667
114,flat,bestech park view city,sector 49,3.00,2383.0,12589.0,Super Built up area 2383(221.39 sq.m.)Built Up...,4,4,3,5.0,North-East,Moderately Old,2383.0,2200.00,2000.00,0,1,0,1,0,1,141,595.750000
120,flat,orchid petals,sector 49,2.35,2033.0,11559.0,Super Built up area 2033(188.87 sq.m.)Built Up...,3,3,3,15.0,West,Relatively New,2033.0,2030.00,1750.00,0,0,0,0,1,2,49,677.666667
124,flat,ambience creacions,sector 22,2.55,1860.0,13710.0,Super Built up area 1860(172.8 sq.m.)Built Up ...,3,3,3,8.0,North-East,Relatively New,1860.0,1600.00,1400.00,0,0,0,0,1,0,125,620.000000
128,flat,ireo uptown,sector 66,1.50,1337.0,11219.0,Super Built up area 1337(124.21 sq.m.)Built Up...,2,3,3,1.0,South,Relatively New,1337.0,1330.00,1050.00,0,1,0,0,1,1,79,668.500000
148,flat,ats tourmaline,sector 109,1.45,2150.0,6744.0,Super Built up area 2150(199.74 sq.m.)Built Up...,3,4,3+,4.0,North-West,Relatively New,2150.0,1797.00,1660.00,0,1,0,0,0,2,71,716.666667
165,flat,the close north,sector 50,2.92,2605.0,11209.0,Super Built up area 2605(242.01 sq.m.)Built Up...,3,3,3,10.0,North,Moderately Old,2605.0,2600.00,2100.00,0,1,0,0,0,1,174,868.333333
168,flat,ireo the grand arch,sector 58,3.83,1775.0,21577.0,Super Built up area 2164(201.04 sq.m.)Built Up...,3,4,2,10.0,North-East,Relatively New,2164.0,2000.00,1775.00,1,1,0,0,0,1,174,591.666667
170,flat,dlf the ultima,sector 81,2.40,2132.0,11257.0,Super Built up area 2132(198.07 sq.m.)Built Up...,3,3,2,10.0,North-West,Relatively New,2132.0,1800.00,1400.00,0,1,0,0,0,0,174,710.666667
171,flat,bestech park view ananda,sector 81,0.95,1360.0,6985.0,Super Built up area 1360(126.35 sq.m.)Built Up...,2,2,2,13.0,South-East,Relatively New,1360.0,1150.00,894.00,0,0,0,0,0,1,167,680.000000
172,flat,emaar palm gardens,sector 83,1.76,1900.0,9263.0,Super Built up area 1900(176.52 sq.m.)Built Up...,3,3,3,5.0,South-East,Relatively New,1900.0,1600.00,1240.04,0,1,0,0,0,1,174,633.333333
190,flat,orris aster court premier,sector 85,1.50,2560.0,5859.0,Super Built up area 2560(237.83 sq.m.)Built Up...,4,5,3+,6.0,West,New Property,2560.0,2017.00,1800.00,0,1,0,0,0,1,28,640.000000
196,flat,shapoorji pallonji joyville gurugram,sector 102,2.15,1692.0,12707.0,Super Built up area 1692(157.19 sq.m.)Built Up...,3,3,3,10.0,South-West,Relatively New,1692.0,1690.00,1592.00,0,0,0,0,0,1,49,564.000000
198,flat,m3m ikonic,sector 68,1.80,1950.0,9231.0,Super Built up area 1950(181.16 sq.m.)Built Up...,3,3,3+,18.0,North-East,Relatively New,1950.0,1845.00,1530.00,0,0,0,0,0,1,126,650.000000
199,flat,m3m woodshire,sector 107,1.20,1943.0,6176.0,Super Built up area 1943(180.51 sq.m.)Built Up...,3,3,3,7.0,South,Relatively New,1943.0,1750.00,1550.00,0,0,0,0,0,1,49,647.666667
202,flat,tata primanti,sector 72,6.75,3500.0,19286.0,Super Built up area 4250(394.84 sq.m.)Built Up...,4,4,3+,0.0,North-East,New Property,4250.0,4000.00,3500.00,0,1,0,0,0,1,174,875.000000
209,flat,la vida by tata housing,sector 113,3.05,2690.0,11338.0,Super Built up area 2690(249.91 sq.m.)Built Up...,3,4,3,15.0,North-East,New Property,2690.0,2600.00,2240.00,0,1,0,0,0,2,174,896.666667
226,flat,experion the heartsong,sector 108,1.20,1758.0,6826.0,Super Built up area 1758(163.32 sq.m.)Built Up...,3,3,3+,10.0,South,Relatively New,1758.0,1275.53,974.68,1,0,0,0,0,2,93,586.000000
238,flat,vatika gurgaon,sector 83,0.98,1200.0,8167.0,Super Built up area 1445(134.24 sq.m.)Built Up...,2,2,3,5.0,South,Relatively New,1445.0,1300.00,1200.00,0,0,0,0,0,1,96,600.000000
262,flat,shree arihant apartment,sector 54,1.50,1850.0,8108.0,Super Built up area 1850(171.87 sq.m.)Built Up...,3,3,3+,4.0,West,Moderately Old,1850.0,1700.00,1550.00,0,0,0,1,0,1,75,616.666667
279,flat,meditech apartment,sector 56,2.45,3000.0,8167.0,Super Built up area 3000(278.71 sq.m.)Built Up...,4,4,3+,1.0,West,Relatively New,3000.0,2900.00,2800.00,0,0,0,0,1,1,118,750.000000
331,flat,smart world orchard,sector 61,1.90,837.0,22700.0,Super Built up area 1398(129.88 sq.m.)Built Up...,3,3,3,1.0,NaN,New Property,1398.0,1137.00,837.00,0,0,0,0,0,2,30,279.000000
334,flat,capital residences 360,sector 70a,1.15,1000.0,11500.0,Super Built up area 1450(134.71 sq.m.)Built Up...,2,2,3,4.0,East,New Property,1450.0,1400.00,1000.00,0,0,0,1,0,2,132,500.000000
341,flat,godrej aria,sector 79,1.00,1503.0,6653.0,Super Built up area 1503(139.63 sq.m.)Built Up...,2,2,2,4.0,North-West,Relatively New,1503.0,1300.00,1200.00,1,0,0,0,0,2,49,751.500000
350,flat,ats kocoon,sector 109,1.70,1745.0,9742.0,Super Built up area 1745(162.12 sq.m.)Built Up...,3,3,3,21.0,West,Moderately Old,1745.0,1550.00,1250.00,0,0,0,0,0,2,49,581.666667
355,flat,dlf regal gardens,sector 90,1.25,1540.0,8117.0,Super Built up area 1702(158.12 sq.m.)Built Up...,3,3,3,8.0,South-East,Relatively New,1702.0,1640.00,1540.00,0,0,0,1,0,2,158,513.333333
360,flat,pioneer park,sector 61,2.04,1395.0,14624.0,Super Built up area 1795(166.76 sq.m.)Built Up...,3,3,3+,16.0,South,Moderately Old,1795.0,1595.00,1395.00,0,1,0,0,0,1,165,465.000000
368,flat,m3m skywalk,sector 74,1.55,1124.0,13790.0,Super Built up area 1406(130.62 sq.m.)Built Up...,2,2,3+,18.0,South,Relatively New,1406.0,1300.00,1124.00,0,0,0,0,1,2,137,562.000000
378,flat,experion the heartsong,sector 108,0.90,1283.0,7015.0,Super Built up area 1283(119.19 sq.m.)Built Up...,2,3,3,2.0,South,Relatively New,1283.0,978.23,734.43,0,1,0,0,0,2,94,641.500000
380,flat,bhagwati sadan,sector 12,1.15,2000.0,5750.0,Super Built up area 2500(232.26 sq.m.)Built Up...,3,4,2,2.0,NaN,Old Property,2500.0,2000.00,1750.00,1,1,0,0,1,1,28,666.666667
382,flat,ats kocoon,sector 109,1.65,1550.0,10645.0,Super Built up area 1745(162.12 sq.m.)Built Up...,3,3,3,19.0,East,Relatively New,1745.0,1650.00,1550.00,0,0,1,0,0,1,159,516.666667
390,flat,spaze privy at,sector 84,1.35,1400.0,9643.0,Super Built up area 1918(178.19 sq.m.)Built Up...,3,3,3,7.0,South-East,Relatively New,1918.0,1750.00,1400.00,0,0,0,1,0,2,90,466.666667
411,flat,vatika gurgaon,sector 83,1.12,1735.0,6455.0,Super Built up area 1735(161.19 sq.m.)Built Up...,3,3,2,17.0,South,Moderately Old,1735.0,1500.00,1400.00,0,0,0,0,0,1,111,578.333333
417,flat,ss the leaf,sector 85,1.18,1100.0,10727.0,Super Built up area 1741(161.74 sq.m.)Built Up...,2,2,3,9.0,North-East,Relatively New,1741.0,1700.00,1100.00,1,0,0,0,0,1,150,550.000000
424,flat,vatika gurgaon,sector 83,1.10,1785.0,6162.0,Super Built up area 1785(165.83 sq.m.)Built Up...,3,3,3+,5.0,North-West,Relatively New,1785.0,1600.00,1500.00,0,0,0,0,0,1,96,595.000000
437,flat,vatika gurgaon,sector 83,1.25,1980.0,6313.0,Super Built up area 1980(183.95 sq.m.)Built Up...,3,3,2,12.0,North,Moderately Old,1980.0,1700.00,1400.00,0,1,0,0,0,2,95,660.000000
440,flat,emaar gurgaon greens,sector 102,1.40,1650.0,8485.0,Super Built up area 1650(153.29 sq.m.)Built Up...,3,3,3,10.0,East,Relatively New,1650.0,1300.00,1022.58,0,1,0,0,0,2,46,550.000000
443,flat,emaar gurgaon greens,sector 102,1.35,1250.0,10800.0,Super Built up area 1650(153.29 sq.m.)Built Up...,3,4,3+,9.0,North-East,Relatively New,1650.0,1400.00,1250.00,0,1,0,1,0,1,174,416.666667
458,flat,ss the leaf,sector 85,2.03,2808.0,7229.0,Super Built up area 2812(261.24 sq.m.)Built Up...,4,4,3+,3.0,North-East,Relatively New,2812.0,2225.00,2175.00,0,0,0,0,1,2,49,702.000000
462,flat,ss the coralwood,sector 84,1.05,1550.0,6774.0,Super Built up area 1750(162.58 sq.m.)Built Up...,3,3,3,6.0,North-East,Relatively New,1750.0,1610.00,1550.00,0,0,0,0,1,2,129,516.666667
469,flat,dlf the ultima,sector 81,2.25,2092.0,10755.0,Super Built up area 2092(194.35 sq.m.)Built Up...,3,4,3+,11.0,West,Relatively New,2092.0,2090.00,2087.00,0,1,0,0,0,0,174,697.333333
470,flat,ansal maple crescent,sector 43,1.35,1345.0,10037.0,Super Built up area 1345(124.95 sq.m.)Built Up...,3,3,3,2.0,South,Old Property,1345.0,1320.00,1300.00,0,0,0,0,1,1,93,448.333333
478,flat,gls arawali homes,sohna road,0.28,567.0,4938.0,Super Built up area 567(52.68 sq.m.)Built Up a...,2,2,2,3.0,East,Relatively New,567.0,500.00,467.00,0,0,0,0,0,1,42,283.500000
483,flat,emaar mgf emerald estate,sector 65,1.42,1020.0,13922.0,Super Built up area 1020(94.76 sq.m.)Built Up ...,2,2,2,6.0,North-East,Relatively New,1020.0,1010.00,750.00,1,0,0,0,0,1,174,510.000000
486,flat,signature global solera,sector 107,0.50,1050.0,4762.0,Super Built up area 1050(97.55 sq.m.)Built Up ...,3,2,2,5.0,South,Relatively New,1050.0,850.00,645.00,0,0,0,0,1,2,35,350.000000
492,flat,shree arihant apartment,sector 54,1.55,2100.0,7381.0,Super Built up area 2100(195.1 sq.m.)Built Up ...,3,3,3+,3.0,North-East,Moderately Old,2100.0,2000.00,1900.00,0,0,0,1,1,1,125,700.000000
496,flat,apna enclave,sector 3,0.58,950.0,6105.0,Super Built up area 950(88.26 sq.m.)Built Up a...,2,2,2,2.0,North-East,Old Property,950.0,900.00,744.00,0,0,0,0,0,2,66,475.000000
501,flat,ats tourmaline,sector 109,1.50,2150.0,6977.0,Super Built up area 2150(199.74 sq.m.)Built Up...,3,4,3+,4.0,North-West,Relatively New,2150.0,1797.00,1670.00,0,1,0,0,0,2,39,716.666667
502,flat,adani m2k oyster grande,sector 102,2.50,3198.0,7817.0,Super Built up area 3198(297.1 sq.m.)Built Up ...,4,5,3+,10.0,North-East,Relatively New,3198.0,2600.00,2350.00,0,1,0,1,0,1,174,799.500000
504,flat,ss the leaf,sector 85,2.20,1968.0,11179.0,Super Built up area 2812(261.24 sq.m.)Built Up...,4,5,3+,4.0,West,Relatively New,2812.0,2390.00,1968.00,0,1,0,1,0,2,174,492.000000
515,flat,experion windchants,sector 112,2.80,2441.0,11471.0,Super Built up area 2441(226.78 sq.m.)Built Up...,2,3,2,9.0,South-East,Relatively New,2441.0,1939.03,1800.00,1,1,0,0,0,2,137,1220.500000
523,flat,ambience creacions,sector 22,1.99,1280.0,15547.0,Super Built up area 1380(128.21 sq.m.)Built Up...,2,2,2,9.0,North-East,New Property,1380.0,1285.00,1280.00,0,0,0,0,0,2,49,640.000000
524,flat,bestech spa signature,sector 81,4.45,4200.0,10595.0,Super Built up area 4200(390.19 sq.m.)Built Up...,4,4,3+,8.0,South-West,Relatively New,4200.0,3850.00,3600.00,1,1,0,1,1,1,49,1050.000000
536,flat,ansal maple heights,sector 43,1.50,1185.0,12658.0,Super Built up area 1400(130.06 sq.m.)Built Up...,3,3,3+,7.0,North-East,Old Property,1400.0,1385.00,1185.00,0,0,1,0,0,1,174,395.000000
537,flat,dlf regency park,sector 28,2.25,1550.0,14516.0,Super Built up area 1777(165.09 sq.m.)Built Up...,3,3,2,16.0,West,Old Property,1777.0,1700.00,1550.00,0,1,0,0,0,2,89,516.666667
538,flat,godrej,sector 79,1.12,1567.0,7147.0,Super Built up area 1572(146.04 sq.m.)Built Up...,2,2,3,6.0,North-East,Relatively New,1572.0,1325.00,1200.00,1,0,0,0,0,2,49,783.500000
556,flat,dlf regal gardens,sector 90,1.24,1755.0,7066.0,Super Built up area 1755(163.04 sq.m.)Built Up...,3,3,3+,9.0,South,Relatively New,1755.0,1600.00,1400.00,0,0,0,0,1,2,72,585.000000
561,flat,paras dews,sector 106,1.13,1764.0,6406.0,Super Built up area 1760(163.51 sq.m.)Built Up...,3,4,3+,18.0,North-West,Relatively New,1760.0,1186.00,1130.00,1,1,0,0,0,2,49,588.000000
565,flat,la vida by tata housing,sector 113,2.78,2450.0,11347.0,Super Built up area 2690(249.91 sq.m.)Built Up...,3,3,3,3.0,North,New Property,2690.0,2599.00,2450.00,1,1,0,0,0,2,174,816.666667
581,flat,corona optus,sector 37c,1.25,1763.0,7090.0,Super Built up area 1763(163.79 sq.m.)Built Up...,3,3,3,4.0,North-West,Relatively New,1763.0,1350.00,1234.00,0,0,0,0,1,2,49,587.666667
598,flat,the close north,sector 50,2.35,2069.0,11358.0,Super Built up area 2069(192.22 sq.m.)Built Up...,3,3,3,8.0,North-West,Moderately Old,2069.0,1900.00,1800.00,0,0,0,0,0,1,49,689.666667
599,flat,orris aster court premier,sector 85,1.20,2120.0,5660.0,Super Built up area 2120(196.95 sq.m.)Built Up...,3,4,2,6.0,North-East,Relatively New,2120.0,1650.00,1550.00,0,1,0,0,0,2,28,706.666667
615,flat,ireo victory valley,sector 67,2.99,2527.0,11832.0,Super Built up area 2527(234.77 sq.m.)Built Up...,3,3,3,4.0,East,Relatively New,2527.0,2200.00,2100.00,0,1,0,0,0,1,37,842.333333
638,flat,experion windchants,sector 112,4.25,3763.0,11294.0,Super Built up area 3763(349.59 sq.m.)Built Up...,3,5,2,15.0,South,Relatively New,3763.0,3000.00,2800.00,0,1,0,1,0,2,72,1254.333333
640,flat,tata primanti,sector 72,4.00,2905.0,13769.0,Super Built up area 2905(269.88 sq.m.)Built Up...,4,5,3+,9.0,North-East,Relatively New,2905.0,2800.00,2500.00,0,1,0,0,0,1,165,726.250000
641,flat,m3m golfestate,sector 65,5.00,3000.0,16667.0,Super Built up area 3246(301.56 sq.m.)Built Up...,3,3,3,2.0,East,Relatively New,3246.0,3245.00,3000.00,0,1,0,0,0,1,174,1000.000000
642,flat,pivotal devaan,sector 84,0.41,583.0,7033.0,Super Built up area 583(54.16 sq.m.)Built Up a...,2,2,2,10.0,East,New Property,583.0,565.00,483.00,0,0,0,0,0,1,23,291.500000
647,flat,ireo skyon,sector 60,2.65,2019.0,13125.0,Super Built up area 2045(189.99 sq.m.)Built Up...,3,4,3+,7.0,North-East,Moderately Old,2045.0,2037.00,2019.00,0,1,0,0,0,1,152,673.000000
648,flat,emaar mgf the palm drive,sector 66,3.50,2201.0,15902.0,Super Built up area 2201(204.48 sq.m.)Built Up...,3,3,2,4.0,South,Relatively New,2201.0,2200.00,1800.00,1,0,0,0,0,2,89,733.666667
654,flat,bestech park view grand spa,sector 81,2.30,2660.0,8647.0,Super Built up area 2660(247.12 sq.m.)Built Up...,3,4,3+,7.0,East,Relatively New,2660.0,2280.00,1950.00,0,1,0,0,0,1,49,886.666667
666,flat,supertech araville,sector 79,1.35,1500.0,9000.0,Super Built up area 1530(142.14 sq.m.)Built Up...,2,2,3,6.0,East,New Property,1530.0,1350.00,1200.00,1,0,0,0,1,1,88,750.000000
668,flat,signature global solera,sector 107,0.36,602.0,5980.0,Super Built up area 602(55.93 sq.m.)Built Up a...,2,2,1,7.0,North-West,Relatively New,602.0,598.00,546.00,0,0,0,0,1,2,49,301.000000
671,flat,la vida by tata housing,sector 113,2.35,2217.0,10600.0,Super Built up area 2217(205.97 sq.m.)Built Up...,3,3,3,11.0,North-East,New Property,2217.0,2210.00,1720.00,0,1,0,0,0,2,174,739.000000
692,flat,vatika the seven lamps,sector 82,1.37,1565.0,8754.0,Super Built up area 2160(200.67 sq.m.)Built Up...,3,3,3,11.0,South,Relatively New,2160.0,2000.00,1565.00,1,1,0,1,0,1,145,521.666667
698,flat,tata primanti,sector 72,3.30,2145.0,15385.0,Super Built up area 2145(199.28 sq.m.)Built Up...,3,3,3+,10.0,North-East,Relatively New,2145.0,2000.00,1800.00,0,1,0,0,0,1,165,715.000000
702,flat,vatika gurgaon,sector 83,0.83,1245.0,6667.0,Super Built up area 1245(115.66 sq.m.)Built Up...,2,2,2,12.0,North,Relatively New,1245.0,1154.00,945.00,0,0,0,1,0,2,165,622.500000
703,flat,dlf the icon,sector 43,5.25,2575.0,20388.0,Super Built up area 2575(239.23 sq.m.)Built Up...,4,4,3,9.0,North,Old Property,2575.0,2570.00,2560.00,0,1,0,1,1,2,135,643.750000
706,flat,paras dews,sector 106,1.28,1760.0,7273.0,Super Built up area 1760(163.51 sq.m.)Built Up...,3,4,3+,24.0,North-West,Relatively New,1760.0,1186.00,1130.00,0,1,0,0,0,2,49,586.666667
718,flat,ss,sector 85,2.14,2812.0,7610.0,Super Built up area 2812(261.24 sq.m.)Built Up...,4,4,3,6.0,North,Relatively New,2812.0,2300.00,2000.00,1,1,0,1,0,2,49,703.000000
720,flat,the close north,sector 50,2.35,1997.0,11768.0,Super Built up area 1997(185.53 sq.m.)Built Up...,3,3,3+,8.0,North-East,Moderately Old,1997.0,1950.00,1850.00,0,0,0,0,0,1,165,665.666667
723,flat,valley view estate,gwal pahari,1.50,2003.0,7489.0,Super Built up area 2000(185.81 sq.m.)Built Up...,4,4,3+,10.0,North-East,Moderately Old,2000.0,1850.00,1650.00,0,0,0,0,0,2,58,500.750000
724,flat,unitech harmony,sector 50,2.60,2711.0,9591.0,Super Built up area 2711(251.86 sq.m.)Built Up...,3,4,2,15.0,North-East,Relatively New,2711.0,2700.00,2200.00,0,1,0,0,1,1,174,903.666667
730,flat,eldeco accolade,sohna road,0.95,1538.0,6177.0,Super Built up area 1457(135.36 sq.m.)Built Up...,2,2,3+,8.0,South,Under Construction,1457.0,1050.00,849.00,1,0,0,0,1,2,72,769.000000