## **Preprocessing independent houses dataset**

In [19]:
# importing required dataset
import pandas as pd
import numpy as np
import re

In [3]:
data = pd.read_csv('../data/independent-house.csv')

In [4]:
data.head()

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,...,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,...,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,...,"Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/10-bhk-bedroom-indepen...,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,...,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,https://www.99acres.com/21-bhk-bedroom-indepen...,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,...,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/12-bhk-bedroom-indepen...,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,...,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [5]:
# checking the missing values
data.isnull().sum()

property_name        0
link                 0
society            624
price              127
rate                41
area                 0
areaWithType       108
bedRoom            108
bathroom           108
balcony            108
additionalRoom     506
address             64
noOfFloor          128
facing             421
agePossession      108
nearbyLocations    182
description         59
furnishDetails     352
features           421
rating             188
property_id         59
dtype: int64

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1095 non-null   object
 1   link             1095 non-null   object
 2   society          471 non-null    object
 3   price            968 non-null    object
 4   rate             1054 non-null   object
 5   area             1095 non-null   object
 6   areaWithType     987 non-null    object
 7   bedRoom          987 non-null    object
 8   bathroom         987 non-null    object
 9   balcony          987 non-null    object
 10  additionalRoom   589 non-null    object
 11  address          1031 non-null   object
 12  noOfFloor        967 non-null    object
 13  facing           674 non-null    object
 14  agePossession    987 non-null    object
 15  nearbyLocations  913 non-null    object
 16  description      1036 non-null   object
 17  furnishDetails   743 non-null    object
 18  features         674 non-null    object
 19  rating           907 non-null    object
 20  property_id      1036 non-null   object
dtypes: object(21)
memory usage: 179.8+ KB

In [7]:
# checking for duplicates
data.duplicated().sum()

np.int64(13)

In [8]:
data.drop(columns=['link','property_id'], inplace=True)

In [9]:
data.head(2)

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN

In [10]:
# checking the shape of the dataset
data.shape

(1095, 19)

## **Preprocessing**

In [12]:
data.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [13]:
# renaming the 'rate' column to 'price_per_sqft'
data.rename(columns={'rate':'price_per_sqft'}, inplace=True)

In [16]:
data['price_per_sqft'] = data['price_per_sqft'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip().astype('float')

In [17]:
data['price_per_sqft'].value_counts()

price_per_sqft
22222.0    14
11111.0    12
33333.0    11
10000.0    10
13333.0     7
           ..
13034.0     1
38150.0     1
28782.0     1
34491.0     1
10838.0     1
Name: count, Length: 776, dtype: int64

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1095 non-null   object
 1   society          471 non-null    object
 2   price            968 non-null    object
 3   price_per_sqft   1054 non-null   float64
 4   area             1095 non-null   object
 5   areaWithType     987 non-null    object
 6   bedRoom          987 non-null    object
 7   bathroom         987 non-null    object
 8   balcony          987 non-null    object
 9   additionalRoom   589 non-null    object
 10  address          1031 non-null   object
 11  noOfFloor        967 non-null    object
 12  facing           674 non-null    object
 13  agePossession    987 non-null    object
 14  nearbyLocations  913 non-null    object
 15  description      1036 non-null   object
 16  furnishDetails   743 non-null    object
 17  features         674 non-null    object
 18  rating           907 non-null    object
dtypes: float64(1), object(18)
memory usage: 162.7+ KB

In [11]:
data['society'].value_counts()

society
Vipul Tatvam Villa                     27
Emaar MGF Marbella                     26
International City by SOBHA Phase 2    26
International City by Sobha Phase 1    23
Unitech Uniworld Resorts               14
                                       ..
Ansal Sushant Lok 2                     1
Sector 57 Huda                          1
Godrej Meridien                         1
Huda                                    1
Huda Floor                              1
Name: count, Length: 188, dtype: int64

In [23]:
data['society'] = data['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [25]:
data[data['society']=='nan']

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1,5 Bedroom House for sale in Sector 21A Faridabad,nan,5.7 Crore,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,nan,2.1 Crore,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,nan,5 Crore,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,nan,3 Crore,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
5,20 Bedroom House for sale in Sushant Lok Phase 1,nan,4.5 Crore,39062.0,(107 sq.m.) Plot Area,Plot area 128(107.02 sq.m.),20 Bedrooms,20 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",4 Floors,East,1 to 5 Year Old,"['Huda city centre metro station', 'New Life C...",Best for investment purpose. 3l rupees monthly...,"['1 Water Purifier', '1 Fridge', '20 Fan', '1 ...","['Water Storage', 'Park', 'Visitor Parking', '...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1082,5 Bedroom House for sale in Sector 46 Gurgaon,nan,3.6 Crore,24845.0,(135 sq.m.) Plot Area,Plot area 161(134.62 sq.m.),5 Bedrooms,5 Bathrooms,3+ Balconies,Servant Room,"Sector 46 Gurgaon, Gurgaon, Haryana",3 Floors,South-East,5 to 10 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...",161 square yard built up property available fo...,"['5 Wardrobe', '10 Fan', '1 Exhaust Fan', '50 ...","['Private Garden / Terrace', 'High Ceiling Hei...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1083,5 Bedroom House for sale in Sushant Lok Phase 2,nan,3.1 Crore,20026.0,(144 sq.m.) Plot Area,Plot area 172(143.81 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,"Servant Room,Store Room","Sushant Lok Phase 2, Gurgaon, Haryana",2 Floors,North-East,5 to 10 Year Old,"['Mg road metro station', 'Iffco chowk metro s...",172 square yard built up house for sale in sus...,"['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '2 Ge...","['High Ceiling Height', 'False Ceiling Lightin...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1084,3 Bedroom House for sale in Sushant Lok Phase 3,nan,4.75 Crore,28787.0,(149 sq.m.) Plot Area,Plot area 1600(148.64 sq.m.)Built Up area: 170...,3 Bedrooms,3 Bathrooms,3 Balconies,Store Room,240 Sq.Yrd Old Siplex 3 Bhk Villa In Gated Blo...,2 Floors,North-West,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Sanatan Dharm M...",240 sq.Yrd park facing simplex 3 bhk villa for...,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '11 L...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1092,8 Bedroom House for sale in DLF Phase 2,nan,NaN,23457.0,(376 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1093,8 Bedroom House for sale in C Block Sushant Lo...,nan,NaN,31008.0,(180 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
data['society'] = data['society'].str.replace('nan','independent')

In [28]:
data['society'].value_counts()

society
independent                            624
vipul tatvam villa                      27
emaar mgf marbella                      26
international city by sobha phase 2     26
international city by sobha phase 1     23
                                      ...
ansal sushant lok 2                      1
sector 57 huda                           1
godrej meridien                          1
huda                                     1
huda floor                               1
Name: count, Length: 186, dtype: int64

**`price` column**

In [29]:
data['price'].value_counts()

price
3.5 Crore     19
5.5 Crore     17
6.5 Crore     16
6 Crore       14
5 Crore       13
              ..
3.8 Crore      1
7.45 Crore     1
7.42 Crore     1
6.09 Crore     1
2.98 Crore     1
Name: count, Length: 302, dtype: int64

In [30]:
data = data[data['price']!='Price on Request']

In [31]:
# Creating a price convertor function
def price_converter(x):
    """
    This function converts price amounts into Crores.
    """
    # If the input is already a float, return it directly
    if isinstance(x, float):
        return x

    # Split the string into parts
    parts = x.split(' ')

    # Check if the split resulted in at least two parts
    if len(parts) < 2:
        return None  # Or handle it in another way, like returning 0

    # Extract the numeric value and unit
    numeric_value = float(parts[0])
    unit = parts[1]

    # Convert based on the unit
    if unit == 'Lac':
        return round(numeric_value / 100, 2)
    elif unit == 'Crore':
        return round(numeric_value, 2)
    else:
        return None  # Handle unexpected units

In [32]:
# Applying the price converter function to the price feature
data['price'] = data['price'].apply(price_converter)

In [33]:
data.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

**`area` column**

In [34]:
data['area'].value_counts()

area
(301 sq.m.) Plot Area    46
(84 sq.m.) Plot Area     40
(251 sq.m.) Plot Area    34
(167 sq.m.) Plot Area    27
(420 sq.m.) Plot Area    26
                         ..
(181 sq.m.) Plot Area     1
(509 sq.m.) Plot Area     1
(159 sq.m.) Plot Area     1
(234 sq.m.) Plot Area     1
(537 sq.m.) Plot Area     1
Name: count, Length: 384, dtype: int64

In [39]:
data['area'].str.split(' ').str.get(0).str.replace('(','').str.strip()

0       242
1        50
2        51
3       108
4        52
       ...
1090    226
1091    226
1092    376
1093    180
1094     89
Name: area, Length: 1085, dtype: object